service: rodeo-serverless-test

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: app.app
